-- Fallback color mapping for common color names (Helix named colors)
return {
    ['default'] = nil,
    ['black'] = '#000000',
    ['red'] = '#ff0000',
    ['green'] = '#00ff00',
    ['yellow'] = '#ffff00',
    ['blue'] = '#0000ff',
    ['magenta'] = '#ff00ff',
    ['cyan'] = '#00ffff',
    ['gray'] = '#808080',
    ['grey'] = '#808080',
    ['white'] = '#ffffff',
    ['light-red'] = '#ff6b6b',
    ['light-green'] = '#90ee90',
    ['light-yellow'] = '#ffffe0',
    ['light-blue'] = '#add8e6',
    ['light-magenta'] = '#dda0dd',
    ['light-cyan'] = '#e0ffff',
    ['light-gray'] = '#d3d3d3',
    ['light-grey'] = '#d3d3d3',
    ['dark-gray'] = '#a9a9a9',
    ['dark-grey'] = '#a9a9a9',
}
